### ISSUE TITLE
[Bug] Delete device in runtime doesn´t stop gathering process

### ISSUE THREAD

**Issue by wurmrobert** [toni-moreno/snmpcollector#444]
- SnmpCollector version: 0.8.0
- Running on docker ubuntu 16.04

In spite of the issue #349 i got the behaviour that the gathering process after `DeleteDeviceInRuntime` is not stopped.

In the `snmpdevice` bus message [syncexit](https://github.com/toni-moreno/snmpcollector/blob/2ed85980ba75ccc16445f905949344fb31f6c66a/pkg/agent/device/snmpdevice.go#L748) the `isStopped` is set to true.

But the gathering loop doesn´t stop after the `syncexit` and therefore the device is not removed from the gathering process.
For me it looks like an infinite gathering loop.

Any ideas?

**Comment by sbengo** [comment]
Hi @wurmrobert , thanks for submitting this

Its so strange, the process of `DeleteDeviceInRuntime` is done on the following function, direclty on the agent:

https://github.com/toni-moreno/snmpcollector/blob/2ed85980ba75ccc16445f905949344fb31f6c66a/pkg/agent/agent.go#L255-L269

After the message `syncexit` it releases the bus and delete the device from the runtime devices array, so the device should be  removed from gathering proces.
I have made some test and it is being removed correctly, but just could test on an instance with few devices

In order to keep reviewing a possible bug, can you please, provide the following information:

- Can you tell us the frequency that the device is not being removed from the gathering process after a DeleteDeviceInRuntime? Is it happening all time?
- How many devices do you have enabled on the instance?
- Can you provide logs when the device is not being removed from gathering process (on debug)?

Thanks,
Regards!

**Comment by wurmrobert** [comment]
Hi @sbengo. 
I tested it with more than 1000 devices and also with only 1 device.
During this tests i saw the mistake.

I add the devices with your api `post /api/cfg/snmpdevice/full`. The problem was that i added every device twice. Thereby each device has exists twice in the runtime and each device was only visible once (i think through the same id) in your web ui.

So i fixed to add the device only once and now the gathering process stops correctly.

Thanks for you help!

**Comment by toni-moreno** [comment]
Hello @wurmrobert snmpcollector should not be able to insert twice with the same id. If so this behavior should be fixed

**Comment by toni-moreno** [comment]
Hello @wurmrobert I've tested and verified that can not insert twice the same id, the request will fail with a db  unique constraint error. 

```
[Macaron] 2020-10-06 06:15:02: Completed GET /api/cfg/snmpdevice 200 OK in 7.076395ms
[Macaron] 2020-10-06 06:17:26: Started POST /api/cfg/snmpdevice/ for 127.0.0.1
time="2020-10-06 06:17:26" level=info msg="ADDING DEVICE {ID:localhost Host:127.0.0.1 Port:161 SystemOIDs:[] Retries:5 Timeout:20 Repeat:0 Active:true SnmpVersion:2c Community:public V3SecLevel: V3AuthUser: V3AuthPass: V3AuthProt: V3PrivPass: V3PrivProt: V3ContextEngineID: V3ContextName: DisableBulk:false MaxRepetitions:50 Freq:60 UpdateFltFreq:60 ConcurrentGather:true OutDB:influx-robotito LogLevel:info LogFile: SnmpDebug:false DeviceTagName:device DeviceTagValue:id ExtraTags:[] DeviceVars:[] Description: MeasurementGroups:[Linux_Template] MeasFilters:[ifPort_UP diskIODevice_is_fisical linux_hrStorage_is_fs]} mode()"
time="2020-10-06 06:17:26" level=warning msg="Error on insert for device localhost  , affected : 0 , error: UNIQUE constraint failed: snmp_device_cfg.id"
```

>

**Comment by wurmrobert** [comment]
Hi @toni-moreno.

I´m using SQLite DB and i don´t get the unique constraint error.

```
INFO[2020-10-06 10:21:54] ADDING DEVICE {ID:0a77c0fb-4b61-45b0-969b-4ce05e67fc59_live_devices Host:10.46.XX.YY Port:161 SystemOIDs:[] Retries:2 Timeout:5 Repeat:0 Active:true SnmpVersion:2c Community:public V3SecLevel: V3AuthUser: V3AuthPass: V3AuthProt: V3PrivPass: V3PrivProt: V3ContextEngineID: V3ContextName: DisableBulk:false MaxRepetitions:5 Freq:2 UpdateFltFreq:60 ConcurrentGather:true OutDB:influx LogLevel:error LogFile: SnmpDebug:false DeviceTagName:host DeviceTagValue:host ExtraTags:[] DeviceVars:[] Description:snmp_live_agent MeasurementGroups:[24f83c4e-45b3-4f8a-876e-10cd37aaa63f] MeasFilters:[] SpecificInterfaceFilters: SpecificMetricFilters:docsIfSigQSignalNoise} mode() 
INFO[2020-10-06 10:22:05] Added new Device Successfully with id 0a77c0fb-4b61-45b0-969b-4ce05e67fc59_live_devices [1 Measurment Groups | 0 filters] 
INFO[2020-10-06 10:22:11] ADDING DEVICE {ID:0a77c0fb-4b61-45b0-969b-4ce05e67fc59_live_devices Host:10.46.XX.YY Port:161 SystemOIDs:[] Retries:2 Timeout:5 Repeat:0 Active:true SnmpVersion:2c Community:public V3SecLevel: V3AuthUser: V3AuthPass: V3AuthProt: V3PrivPass: V3PrivProt: V3ContextEngineID: V3ContextName: DisableBulk:false MaxRepetitions:5 Freq:2 UpdateFltFreq:60 ConcurrentGather:true OutDB:influx LogLevel:error LogFile: SnmpDebug:false DeviceTagName:host DeviceTagValue:host ExtraTags:[] DeviceVars:[] Description:snmp_live_agent MeasurementGroups:[24f83c4e-45b3-4f8a-876e-10cd37aaa63f] MeasFilters:[] SpecificInterfaceFilters: SpecificMetricFilters:docsIfSigQSignalNoise} mode() 
INFO[2020-10-06 10:22:15] Updated device constrains (old 1 / new 1 ) Measurement Groups 
INFO[2020-10-06 10:22:15] Updated device constrains (old 0 / new 0 ) MFilters 
INFO[2020-10-06 10:22:15] Updated new Device Successfully with id 0a77c0fb-4b61-45b0-969b-4ce05e67fc59_live_devices and data:{ID:0a77c0fb-4b61-45b0-969b-4ce05e67fc59_live_devices Host:10.46.XX.YY Port:161 SystemOIDs:[] Retries:2 Timeout:5 Repeat:0 Active:true SnmpVersion:2c Community:public V3SecLevel: V3AuthUser: V3AuthPass: V3AuthProt: V3PrivPass: V3PrivProt: V3ContextEngineID: V3ContextName: DisableBulk:false MaxRepetitions:5 Freq:2 UpdateFltFreq:60 ConcurrentGather:true OutDB:influx LogLevel:error LogFile: SnmpDebug:false DeviceTagName:host DeviceTagValue:host ExtraTags:[] DeviceVars:[] Description:snmp_live_agent MeasurementGroups:[24f83c4e-45b3-4f8a-876e-10cd37aaa63f] MeasFilters:[] SpecificInterfaceFilters: SpecificMetricFilters:docsIfSigQSignalNoise} 
```

And after i remove the device the gathering process still continues.
